version: '3'
services:
  dana-main:
    build:
      dockerfile: ./Dockerfile.main
    networks:
      - dana
    ports:
      - 8080:8080
  dana-remote-1:
    build:
      dockerfile: ./Dockerfile.remote
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - APP_PORT=2010
    networks:
      - dana
  dana-remote-2:
    build:
      dockerfile: ./Dockerfile.remote
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - APP_PORT=2011
    networks:
      - dana

networks:
  dana:
    driver: bridge